### ISSUE TITLE
Travis CI account and build script

### ISSUE THREAD

**Issue by luigiberrettini** [graffen/NLog.Targets.Syslog#109]
It would be great if @graffen could create a Travis CI account, shared among mantainers as the one created for AppVeyor

I created PR #108 to provide the build scripts

**Comment by luigiberrettini** [comment]
Hi @graffen can you find some time to devote to this project in the near-term or is this a busy period?

**Comment by graffen** [comment]
Wow, I completely missed this, sorry!!!
Of course I'll help you set up travis-ci :+1:

**Comment by graffen** [comment]
I've created the travis-ci for this repo. I'm unsure if I need to do anything special for you to be able to interact with it. It's at https://travis-ci.org/graffen/NLog.Targets.Syslog

**Comment by luigiberrettini** [comment]
Thanks @graffen I am able to trigger and cancel builds and edit settings 😉
