### ISSUE TITLE
Classic .NET framework dependency

### ISSUE THREAD

**Issue by luigiberrettini** [graffen/NLog.Targets.Syslog#113]
"We are trying to get a grasp on .NET Core and we want to use this package to log to Papertrail. However When using this package in our Core project, it warns us that it has a dependency on the (old) .Net Framework. We do not want to have to install the .NET Framework on our servers, only .NET Core. So, is there a way to get rid of the dependency in this package?" by @troelsaaberg

**Comment by luigiberrettini** [comment]
Which version of the [NLog.Targets.Syslog NuGet package](https://www.nuget.org/packages/NLog.Targets.Syslog) are you using?
Only 5.x supports .NET core and it is still a beta.

**Comment by TroelsAaberg** [comment]
We are using the 4.0.1 version, which is propably why we are experiencing the issue. We will have a look at that test app. thanks.
