### ISSUE TITLE
RFC5234 Time format not respected

### ISSUE THREAD

**Issue by Cottinet** [graffen/NLog.Targets.Syslog#35]
As per RFC5234 [https://tools.ietf.org/html/rfc5424#section-6] the time fraction should have 1 to 6 digit. Time formated by the target uses `DateTime.ToString("o")` which produces a 7 digits time fraction.

It has been reported by one of our customer to be incompatible with their syslog client.

**Comment by luigiberrettini** [comment]
PR #36 fixes this issue

**Comment by graffen** [comment]
Fixed by PR #36
