### ISSUE TITLE
version 2.1.6015.35897 can not send log via tcp

### ISSUE THREAD

**Issue by personball** [graffen/NLog.Targets.Syslog#37]
when I installed version 2.1.5893.18660 every thing was ok, 
but now upgrade to 2.1.6015.35897, It's fail to send log.

**Comment by graffen** [comment]
@personball thanks for your comment. I'll take a look.

**Comment by graffen** [comment]
I won't be home till pretty late though. @luigiberrettini any ideas?

**Comment by luigiberrettini** [comment]
Hi @graffen, my first suggestions for @personball:

1. Does the configuration use the new format?
2. Have you enabled the NLog internal logger?

**Comment by personball** [comment]
Hi, @luigiberrettini ,sorry, I didn't realized things about the configuration format has changed.
I'll check it later,thanks for your help.

**Comment by personball** [comment]
@graffen @luigiberrettini I will update my config file for latest version of NLog.Targets.Syslog, Thanks for your help.
