### ISSUE TITLE
tcp connections will not be close.

### ISSUE THREAD

**Issue by personball** [graffen/NLog.Targets.Syslog#38]
Hi, I use  NLog.Targets.Syslog  to send log into graylog.

I see the graylog count tcp connections as below 

**Active connections: 0 (471,094 total)**

It seems  NLog.Targets.Syslog  will open a new tcp connection to send every message.

Is it a problem that the inactive connections will not be closed?

**Comment by luigiberrettini** [comment]
This behavior is the same of the original @graffen code:
https://github.com/graffen/NLog.Targets.Syslog/blob/c16cadba5e1b693567f557c07ca0fa6a2534fb87/src/NLog.Targets.Syslog/NLog.Targets.Syslog.cs#L151-L168

The using means it should automatically Dispose both TcpClient and the stream:
https://github.com/graffen/NLog.Targets.Syslog/blob/f8c7113f66d3b9e3a70659d6a4ad2aecad3e3883/src/NLog.Targets.Syslog/MessageSend/TcpProtocol.cs#L46-L51

Implementing TCP connection pooling to reduce overhead is more complex but a good reason to create a PR

**Comment by luigiberrettini** [comment]
Fixed by #45
