### ISSUE TITLE
Looking for a new maintainer for NLog.Targets.Syslog

### ISSUE THREAD

**Issue by graffen** [graffen/NLog.Targets.Syslog#46]
I'm looking to add one or more people as contributors to this project since I don't have a lot of free time to take care of it anymore. 
So, those of you that have been submitting PRs lately, if you would like to take over some of the responsibility, I'd be willing to add commit rights to the repo and on Nuget for this package.

**Comment by graffen** [comment]
@luigiberrettini Might this be something you were interested in?

**Comment by luigiberrettini** [comment]
I can handle issues since I worked on it quite thoroughly. As for NuGet I never used it (as a service to build public packages) but I do not think it would be so difficult to learn.

**Comment by luigiberrettini** [comment]
Hi @graffen, is the creation of NuGet package, tag and release automatically done as soon as I merge the 3.0-develop branch on master?
If not how can I perform those activities?

**Comment by graffen** [comment]
@luigiberrettini No you have to create the Nuget package manually. There is a bat file to do so in src\NLog.Targets.Syslog. If you run `build.bat` it just builds the nuget package so you can verify that version numbers etc. are as you expect. If you run `buildtopublic.bat` you'll get it pushed to nuget.org as well. Tagging is also something I've done manually since the version number is only known after msbuild has done its magic. 

Do you have a nuget.org user? I will add you as a maintainer of the package so you're allowed to push it.

**Comment by luigiberrettini** [comment]
Thanks @graffen!
https://www.nuget.org/profiles/luigiberrettini

**Comment by graffen** [comment]
@luigiberrettini Done! I have added you as an owner of the package :)

**Comment by luigiberrettini** [comment]
Sorry @graffen maybe I am doing it wrong but I cannot sort the following problem out:

```shell
Pushing NLog.Targets.Syslog.3.0.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 1913ms
Response status code does not indicate success: 409 (The package ID 'NLog.Targets.Syslog' is not available.).
```

I don't know if this is the problem but I do not see myself as an owner on the NuGet package page:
https://www.nuget.org/packages/NLog.Targets.Syslog/

**Comment by graffen** [comment]
Hi again @luigiberrettini, on nuget.org it says "Pending approval". Perhaps there's an email with a link or you have to log in to nuget.org and do something?

**Comment by luigiberrettini** [comment]
Since I just fixed my e-mail notifications try removing and readding me.

### **Users can contact me through the Contact Owners form**
This subscription allows other registered users of the site to contact you about packages that you own using the Contact Owners form, _**or to request that you become an owner of their package**_.

**Comment by graffen** [comment]
@luigiberrettini sorry been offline for a few days. I just tried to re-add you. Hope it works this time :)

**Comment by 304NotModified** [comment]
This one could be closed? Or do you guys need more maintainers?

**Comment by graffen** [comment]
@304NotModified I think I feel absolutely safe leaving the reigns to @luigiberrettini. He's doing an absolutely awesome job :) Closing this (and if you guys want to remove the request for maintainers from the readme, that's fine too).
