### ISSUE TITLE
Signed Syslog Messages #RFC5848

### ISSUE THREAD

**Issue by AlexK555** [graffen/NLog.Targets.Syslog#48]
Add support of RFC5848 standard implementation to enable signed syslog messages.

**Comment by luigiberrettini** [comment]
Sorry @AlexK555, I read the RFC 5848 and no "user messages" are involved: this is in contrast with the goal of logging and would mean sending syslog messages not related to NLog calls.
Did I miss something?

**Comment by luigiberrettini** [comment]
Closing until more people are asking for it
