### ISSUE TITLE
Add web applications support

### ISSUE THREAD

**Issue by s-scherbinin-parc** [graffen/NLog.Targets.Syslog#49]
https://github.com/graffen/NLog.Targets.Syslog/blob/master/src/NLog.Targets.Syslog/Settings/Rfc5424Config.cs#L46
```
Assembly.GetEntryAssembly().GetName().Name;
```
It's not working.

**Comment by mniak** [comment]
My suggestion would be use the stack trace to find the first non-microsoft library in the stack bottom.
There may be better solutions, but this would solve the problem for most cases, maybe just not for Microsoft developers. 

I'll make a PR with the proposed solutions

**Comment by luigiberrettini** [comment]
Thanks for your PR I am going to review it ASAP: I would like to avoid the stack trace approach and use an extension method to handle all kinds of applications

**Comment by 304NotModified** [comment]
Same issue also reported here ;)

https://github.com/NLog/NLog/issues/1894

**Comment by luigiberrettini** [comment]
Maybe @304NotModified but for sure the configuration file is not ok as I highlighted in #51

**Comment by luigiberrettini** [comment]
Closed by #53
