### ISSUE TITLE
NLog with NLog.Targets.Syslog - Object reference error

### ISSUE THREAD

**Issue by Kalyanr** [graffen/NLog.Targets.Syslog#51]
Iam trying to log to the papertrail systems using Nlog and NLog.Targets.Syslog and somehow Nlog fails to load the target from the Nlog.config when i call

Logger logger = LogManager.GetCurrentClassLogger();

and throws the exception Object reference not set to an instance of an object.

```
at NLog.Targets.Syslog.Settings.Rfc3164Config..ctor()
   at NLog.Targets.Syslog.Settings.MessageBuilderConfig..ctor()
   at NLog.Targets.Syslog.SyslogTarget..ctor()
Stacktrace
at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
   at NLog.LogFactory.LoadLoggingConfiguration(String configFile)
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetCurrentClassLogger()
   at NLogPaperTrail.Controllers.HomeController.Index() in I:\Temp\Proj\tempsolution\NLogPaperTrail\NLogPaperTrail\Controllers
```

This is the Nlog.config

```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true"     ThrowExceptions = "true"  >

 <extensions>

       <add assembly="NLog.Targets.Syslog" />
    </extensions>

    <targets>
        <target name="syslog" xsi:type="Syslog" syslogserver="host.papertrailapp.com" port="5677" facility="Local7"/>

   </targets>

    <rules>

     <logger name="*" minLevel="Trace" appendTo="syslog"/>
    </rules>
</nlog>

```

Can anyone help or provide your suggestions?

**Comment by luigiberrettini** [comment]
A major release has been issued bringing along breaking changes.
Please take a look at the new [configuration settings](https://github.com/graffen/NLog.Targets.Syslog/blob/56b1147700b6c39e0bd1aec8437969b38c2ed77f/README.md).

**Comment by Kalyanr** [comment]
Iam trying to log to papertrail log systems and iam using the same NLog config format which they have published in their website. Can you please let me know which version of NLog.Targets.Syslog works with that NLog target format ? 

```
<extensions>

       <add assembly="NLog.Targets.Syslog" />
    </extensions>

    <targets>
        <target name="syslog" xsi:type="Syslog" syslogserver="host.papertrailapp.com" port="5677" facility="Local7"/>

   </targets>

    <rules>

     <logger name="*" minLevel="Trace" appendTo="syslog"/>
    </rules>
```

**Comment by 304NotModified** [comment]
> A major release has been issued bringing along breaking changes.
> Please take a look at the new configuration settings.

Well it should never throw a nullref exception isn't it? ;)

**Comment by luigiberrettini** [comment]
I have never tried papertrail: try versions below 3.0.0 with that configuration or 3.0.1 looking at our README.
