### ISSUE TITLE
NLog.Targets.Syslog fails to recover when a TCP endpoint drops and then subsequently becomes available.

### ISSUE THREAD

**Issue by JonPaz** [graffen/NLog.Targets.Syslog#52]
When logs are being sent to a syslog endpoint via TCP, that endpoint becomes unavailable (e.g. Service stops or network outage) and then subsequently returns, logs do not get sent to the destination.  Restarting the application rectifies this.

Initial analysis is that the interaction with streams within the Tcp::FramingTask and Tcp::WriteAsync methods can cause an unhandled IOException to be raised upon comms failures.  This appears to upset the AsyncLogger class such that the ProcessQueueAsync method is nolnger invoked (I guess that the unhandled exception is causing the Task hosting the ProcessQueueAsync  method to fail).

Proposed solution is to have specific IOException handling within these 2 methods, which I'll include on a candidate branch.

**Comment by luigiberrettini** [comment]
Thanks @JonPaz!

I thought this scenario was handled by the InitTcpClient in [MessageSend/Tcp.cs](https://github.com/graffen/NLog.Targets.Syslog/blob/56b1147700b6c39e0bd1aec8437969b38c2ed77f/src/NLog.Targets.Syslog/MessageSend/Tcp.cs): I would be really grateful if you could investigate more and let me know what you find out.

**Comment by JonPaz** [comment]
No worries, I'll mod the code on a branch and update the issue to include steps to repeat etc.  Just testing on our dev system at the mo.

**Comment by luigiberrettini** [comment]
Thanks, I tried to reproduce the TCP server intermittent behavior before (using the TestApp and stopping/restarting the server) and then deployed to all our envs solving the issues, but apparently this was not enough 😞

**Comment by JonPaz** [comment]
Hi there Luigi,

Am working with the TestApp server so that I can write self-contained repeatable steps and am having the following issue(s) - would you be able to see if you can repeat and advise on any fixes to the TestApp?

1. Set the _syslogcee-tgt_ logger to use TCP
2. Run TestApp in debugger
3. Start syslog server
4. Send Warning log message -> message appears in TCP window
5. Stop syslog server
6. Start syslog server
7. Send Warning log message -> Get code exception, see image.
![image](https://cloud.githubusercontent.com/assets/6118046/21817771/4087a91c-d75d-11e6-9ad8-c4775366f716.png)

Cheers,

Jon

**Comment by luigiberrettini** [comment]
It works on my computer 😭 

I wait a bit after I stop or start the Server, btw it is not a professional Syslog server...

TestApp config file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:sl="https://github.com/graffen/NLog.Targets.Syslog/tree/master/src/schemas/NLog.Targets.Syslog.xsd">
    <variable name="enterpriseId" value="12345"/>
    <variable name="sequenceId" value="1"/>
    <targets>
        <target xsi:type="sl:Syslog" name="syslogcee-tgt">
            <sl:layout xsi:type="CompoundLayout">
                <layout xsi:type="SimpleLayout" text="@cee: " />
                <layout xsi:type="JsonLayout">
                    <attribute name="env" layout="DEV" />
                    <attribute name="area" layout="Provisioning" />
                    <attribute name="category" layout="Console" />
                    <attribute name="app" layout="TestApp" />
                    <attribute name="message" layout="${message}${newLine}${exception:format=ToString,StackTrace}" />
                </layout>
            </sl:layout>
            <sl:enforcement>
                <sl:throttling>
                    <sl:limit>100000</sl:limit>
                    <sl:strategy>None</sl:strategy>
                    <sl:delay>0</sl:delay>
                </sl:throttling>
                <sl:messageProcessors>0</sl:messageProcessors>
                <sl:splitOnNewLine>false</sl:splitOnNewLine>
                <sl:transliterate>false</sl:transliterate>
                <sl:replaceInvalidCharacters>false</sl:replaceInvalidCharacters>
                <sl:truncateFieldsToMaxLength>true</sl:truncateFieldsToMaxLength>
                <sl:truncateMessageTo>64512</sl:truncateMessageTo>
            </sl:enforcement>
            <sl:messageCreation>
                <sl:facility>Local4</sl:facility>
                <sl:rfc>Rfc5424</sl:rfc>
                <sl:rfc3164 hostname="notUsedHostname" tag="notUsedTag" />
                <sl:rfc5424>
                    <sl:hostname xsi:type="SimpleLayout" text="${machinename}" />
                    <sl:appName xsi:type="SimpleLayout" text="Provisioning" />
                    <sl:procId xsi:type="SimpleLayout" text="Console.TestApp" />
                    <sl:msgId xsi:type="SimpleLayout" text="-" />
                    <sl:disableBom>true</sl:disableBom>
                </sl:rfc5424>
            </sl:messageCreation>
            <sl:messageSend>
                <sl:protocol>TCP</sl:protocol>
                <sl:udp>
                    <sl:server>127.0.0.1</sl:server>
                    <sl:port>1514</sl:port>
                </sl:udp>
                <sl:tcp>
                    <sl:server>127.0.0.1</sl:server>
                    <sl:port>1514</sl:port>
                    <sl:useTls>false</sl:useTls>
                    <sl:framing>octetCounting</sl:framing>
                    <sl:dataChunkSize>8192</sl:dataChunkSize>
                </sl:tcp>
            </sl:messageSend>
        </target>
    </targets>
    <rules>
        <logger name="*" minlevel="Trace" writeTo="syslogcee-tgt" />
    </rules>
</nlog>
``` 

Starting and stopping the server multiple times tcp?.Connected is true and WriteAsync does not throw any exception 😲 
Sometimes it eventually detects it is not connected and the ProcessQueueAsync method of AsyncLogger behaves correctly (t.IsFaulted is true then it calls ProcessQueueAsync again).

Also add this to TestApp app.config:
```xml
<runtime>
    <ThrowUnobservedTaskExceptions enabled="true"/>
</runtime>
```

**Comment by luigiberrettini** [comment]
If you look at my [handle-intermittent-syslog-server](https://github.com/luigiberrettini/NLog.Targets.Syslog/tree/handle-intermittent-syslog-server) branch you can now simulate the erroneous behavior that results in an UnobservedTaskException:
```text
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
   at NLog.Targets.Syslog.MessageSend.Tcp.FramingTask(ByteArray message) in D:\AD\Development\Projects\NLog.Targets.Syslog\src\NLog.Targets.Syslog\MessageSend\Tcp.cs:line 106
   at NLog.Targets.Syslog.MessageSend.Tcp.WriteAsync(ByteArray message, CancellationToken token) in D:\AD\Development\Projects\NLog.Targets.Syslog\src\NLog.Targets.Syslog\MessageSend\Tcp.cs:line 91
   at NLog.Targets.Syslog.MessageSend.Tcp.SendMessageAsync(ByteArray message, CancellationToken token) in D:\AD\Development\Projects\NLog.Targets.Syslog\src\NLog.Targets.Syslog\MessageSend\Tcp.cs:line 44
   at NLog.Targets.Syslog.LogEventMsgSet.SendAsync(CancellationToken token, TaskCompletionSource`1 tcs) in D:\AD\Development\Projects\NLog.Targets.Syslog\src\NLog.Targets.Syslog\LogEventMsgSet.cs:line 51
   at NLog.Targets.Syslog.LogEventMsgSet.SendAsync(CancellationToken token) in D:\AD\Development\Projects\NLog.Targets.Syslog\src\NLog.Targets.Syslog\LogEventMsgSet.cs:line 38
   at NLog.Targets.Syslog.AsyncLogger.ProcessQueueAsync(MessageBuilder messageBuilder) in D:\AD\Development\Projects\NLog.Targets.Syslog\src\NLog.Targets.Syslog\AsyncLogger.cs:line 58
   at NLog.Targets.Syslog.AsyncLogger.<>c__DisplayClass10_0.<ProcessQueueAsync>b__0(Task t) in D:\AD\Development\Projects\NLog.Targets.Syslog\src\NLog.Targets.Syslog\AsyncLogger.cs:line 72
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

I have to further investigate on the behavior of FromAsync and where my code is not catching its exceptions.

**Comment by luigiberrettini** [comment]
Looking at the [nature of task completion sourcet result](http://blogs.msdn.microsoft.com/pfxteam/2009/06/02/the-nature-of-taskcompletionsourcetresult) it seems that when using a **TaskCompletionSource** there is no more automatic handling of exceptions as with **Task.Factory.StartNew**

This means that whatever exception is thrown outside tasks or continuations is not handled and results in an UnobservedTaskException: this generate the need of using **try/catch**.

What I found pretty strange is that the **Task.Factory.FromAsync** method (the root cause of evil 😄) was throwing the underlying Socket or I/O exceptions instead of returning a faulted Task 😞

It would be really great if you could do some tests with the DLL compiled my [handle-intermittent-syslog-server](https://github.com/luigiberrettini/NLog.Targets.Syslog/tree/handle-intermittent-syslog-server) branch, so that I can merge with more confidence.

**Comment by JonPaz** [comment]
Good afternoon Luigi,

I'll give the code from your test branch a go tomorrow. I've also been doing some further investigation here and have come up with some rather interesting results, that may align with what you have found (would be good to know your views).

_I've found that the problem I saw only occurs when sending logs to a REMOTE syslog server._

The test results are as follows:
_What I found for the TestApp was sending to a LOCAL syslog server with _messageProcessors_ set to 1:_
- Messages delivered to the syslog server
- Stop server, results in the destination TCP port being closed
- Log messages
- Unhandled IOException raised within the Tcp:WriteAsync(int offset, ByteArray data, CancellationToken token) method, when the call to 'return Task.Factory' is made
- Log messages
- Messages are enqueued, and AsyncLogger::ProcessQueueAsync is called to take them off of the queue
- Start server
- Log messages
- Messages are delivered to the syslog server

_What I found for the TestApp was sending to a REMOTE syslog server with _messageProcessors_ set to 1:_
- Messages delivered to the syslog server
- Stop server, results in the destination TCP port being closed
- Log messages
- Unhandled IOException raised within the Tcp:FramingTask(ByteArray message) method, when the call to 'return Task.Factory.FromAsync' is made
- Log messages
- Messages are enqueued, and AsyncLogger::ProcessQueueAsync is NOT called to take them off of the queue
- Start server
- Log messages
- Messages are NOT delivered to the syslog server

_What I found for the TestApp was sending to a REMOTE syslog server with _messageProcessors_ set to 1 AND framing set to nonTransparent:_
- Messages delivered to the syslog server
- Stop server, results in the destination TCP port being closed
- Log messages
- Unhandled IOException raised within the Tcp:WriteAsync(int offset, ByteArray data, CancellationToken token) method, when the call to 'return Task.Factory' is made
- Log messages
- Messages are enqueued, and AsyncLogger::ProcessQueueAsync is called to take them off of the queue
- Start server
- Log messages
- Messages are delivered to the syslog server

Note that by setting framing to nonTransparent, the call into Tcp::FramingTask returns before attempting to write to the stream using Task.Factory.FromAsync.  

For some reason the writing to the stream within the Tcp::FramingTask method behaves differently between connections to local and remote servers - which is strange!

Thoughts?

Jon.

**Comment by JonPaz** [comment]
Hi @luigiberrettini,

Have just been testing out your handle-intermittent-syslog-server branch and the addition of the the _SafeFromAsync_ method fixes the issues that I was seeing!  I think that the code changes you added are very useful.  Can I suggest logging when SafeFromAsync encounters an Exception?

![image](https://cloud.githubusercontent.com/assets/6118046/21927685/a58a3ece-d97e-11e6-841d-8ee32a3c5a42.png)

Cheers,

Jon.

**Comment by luigiberrettini** [comment]
Thank you very much @JonPaz!

I would not add that log line since it is already logged in the [ContinueWith of ProcessQueueAsync](http://github.com/graffen/NLog.Targets.Syslog/blob/e03e1c1b576301f28a0bc146529d820a0f427ef8/src/NLog.Targets.Syslog/AsyncLogger.cs#L69)

I found that the unobserved exceptions are the one I observe 😲😲😲😲😲
I added a GUID to a wrapping exception just to understand what was happening and...
Look at the GUIDs below:
```text
NLog: 2017-01-13 19:51:27.8628 Warn Task faulted Exception: System.Exception:
SPOTTED SafeFromAsync EXCEPTION (b0027d51ec094270bfefd6c8a859ce66)
---> System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at NLog.Targets.Syslog.Extensions.TaskExtensions.SafeFromAsync[TArg1,TArg2,TArg3](TaskFactory taskFactory, Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state) in D:\AD\Development\Projects\NLog.Targets.Syslog\src\NLog.Targets.Syslog\Extensions\TaskExtensions.cs:line 53

******************** DANGEROUSLY UNOBSERVED TASK EXCEPTION!!!
System.Exception:
SPOTTED SafeFromAsync EXCEPTION (b0027d51ec094270bfefd6c8a859ce66)
---> System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at NLog.Targets.Syslog.Extensions.TaskExtensions.SafeFromAsync[TArg1,TArg2,TArg3](TaskFactory taskFactory, Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state) in D:\AD\Development\Projects\NLog.Targets.Syslog\src\NLog.Targets.Syslog\Extensions\TaskExtensions.cs:line 53
```

**Comment by luigiberrettini** [comment]
I found the bug causing unobserved task exceptions! 😎 🎉 🎆
