### ISSUE TITLE
Consider using compiled Regex instances in ReplaceKnownValuePolicy to improve performance

### ISSUE THREAD

**Issue by JonPaz** [graffen/NLog.Targets.Syslog#54]
Currently, _ReplaceKnownValuePolicy_ makes use of the static Regex.Replace method with a readonly _searchFor_ value.  Considering the guidance in 'Best Practices for Regular Expressions in the .NET Framework' (https://msdn.microsoft.com/en-us/library/gg578045(v=vs.110).aspx), it would be more performant for the _ReplaceKnownValuePolicy_ class to have instantiate a private (compiled) Regex() instance upon construction and to use this within the _Apply_ method.

**Comment by luigiberrettini** [comment]
If I am not wrong it should become something like this

```csharp
internal class ReplaceKnownValuePolicy : IBasicPolicy<string, string>
{
    private readonly EnforcementConfig enforcementConfig;
    private readonly string searchFor;
    private readonly string searchForRegEx;
    private readonly string replaceWith;

    public ReplaceKnownValuePolicy(EnforcementConfig enforcementConfig, string searchFor, string replaceWith)
    {
        this.enforcementConfig = enforcementConfig;
        this.searchFor = searchFor;
        searchForRegEx = new Regex(searchFor, RegexOptions.Compiled);
        this.replaceWith = replaceWith;
    }

    public bool IsApplicable()
    {
        return enforcementConfig.ReplaceInvalidCharacters && !string.IsNullOrEmpty(searchFor);
    }

    public string Apply(string s)
    {
        if (s.Length == 0)
            return s;

        var replaced = searchForRegEx.Replace(s, replaceWith);
        InternalLogger.Trace($"Replaced '{searchFor}' (if found) with '{replaceWith}' given known value '{s}': '{replaced}'");
        return replaced;
    }
}
```

**Comment by JonPaz** [comment]
Agreed, that's exactly the kind of thing I was thinking of!

A couple of comments.

- In the _Apply_ method, probably should use _if (string.IsNullOrEmpty)_ as the 's' parameter validation check.

- _searchForRegEx_ is of type Regex

- In the _Apply_ method, wrap the call to _InternalLogger.Trace_ with an if statement to only exercise the (relatively expensive) string concatination if Trace is actually enabled [It would be nice if the .Net loggers were to take an action as a parameter that only got invoked if the level was enabled, oh well! ]

if (InternalLogger.IsTraceEnabled)
{
   InternalLogger.Trace(...)
}

**Comment by 304NotModified** [comment]
I would advise not to do this, or not enable it by default and you should benchmark your code at least. 

The static regex methods are already cached. 

The compiled version could lead memory issues. 

We have disabled compiled regexes in NLog by default. 

See https://blog.codinghorror.com/to-compile-or-not-to-compile/

**Comment by 304NotModified** [comment]
See also https://github.com/NLog/NLog/issues/764

**Comment by luigiberrettini** [comment]
Thanks a lot for your suggestion @304NotModified: with this target performance are pretty important!
