### ISSUE TITLE
Consider adding a new specific 'ReplaceNewLinesPolicy'

### ISSUE THREAD

**Issue by JonPaz** [graffen/NLog.Targets.Syslog#55]
It is very possible for application log entries to include new lines characters such as CR, LF (e.g. Within exception stack traces). From testing NLog.Targets.Syslog with an Ubuntu Rsyslog endpoint, I've observed that the characters get converted to octal representation (015, 016) within the logged text.  It is possible to replace these using the _ReplaceKnowValuePolicy_, but it would be nice to have a specific policy for new lines.

**Comment by luigiberrettini** [comment]
This is a bit tricky.

1. You can have {newline} in an NLog layout
2. You can have newlines in log messages

Applying a policy could be harmful:
- nonTransparent framing will split messages on new line
- splitOnNewLine splits on new line
- octetCounting preserves newlines (and maybe the user wants this

**Comment by luigiberrettini** [comment]
Just had a look at RFCs:
- RFC 3164 does not support CR or LF in the `CONTENT` section of the `MSG` part
- RFC 5424 supports an UTF8 `MSG` part therefore CR and LF should not be encoded
