### ISSUE TITLE
Netstandard / .net core

### ISSUE THREAD

**Issue by 304NotModified** [graffen/NLog.Targets.Syslog#57]
Any plans to support this?

Ps. You will need a reference to NLog 5 beta then.

**Comment by luigiberrettini** [comment]
I would like to add support for .NET core, but I was waiting for a stable NLog release based on .NET Standard and if it comes soon a .NET 4.6.x version with support for .NET Standard 1.6

**Comment by 304NotModified** [comment]
stable NLog will be after NETSTANDARD 2.0 unfortunately. We are missing some APIs.

I think it would be nice to start already with converting, as moving to NETSTANDARD could be time consuming.

**Comment by JonPaz** [comment]
This would certainly be useful as we're also now starting to look at moving more towards .NET Core for future work.

**Comment by luigiberrettini** [comment]
@JonPaz do you fancy working together on this: it is not urgent we can do as much as we can 😉

**Comment by JonPaz** [comment]
Appologies - Missed your original message, sorry!

Yep, very happy to give a hand with doing this - Let me know how I can help!

**Comment by 304NotModified** [comment]
I think a good start is to 

- OR move to VS2017 (rc)
- OR move to project.json (which is a obsolete already).

And then including NLog 5 (beta)

**Comment by luigiberrettini** [comment]
I would prefer creating a dotnetcore branch on which we use VS 2017 and .net standard with nlog 5 targeting .net 4.5/4.6 (the lowest working).
I do not understand the "reference NLog 4.4.x" suggestion: I think we cannot reference both 5.x and 4.x am I right?

**Comment by 304NotModified** [comment]
You could with different platforms (netstandard and net45)

**Comment by 304NotModified** [comment]
For example, https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/project.json

(Legacy project.json format)

**Comment by luigiberrettini** [comment]
Now I understand what you meant 😉

**Comment by 304NotModified** [comment]
:+1:

**Comment by luigiberrettini** [comment]
It seems that also the new csproj supports multitargeting 🎉

**Comment by 304NotModified** [comment]
Yes with vs2017 rc1.

**Comment by JonPaz** [comment]
Just looking at VS2017 RCs and this multi-target feature looks really useful, off to download the installer to play with now.  I agree that a seperate branch core development branch would be  the way forward.

**Comment by luigiberrettini** [comment]
I do not know if I will have time for this issue, but I would start from the RTM version of VS 2017 that will be out in March

**Comment by snakefoot** [comment]
Have made an attempt on this conversion here: #94

**Comment by 304NotModified** [comment]
PS there is a rc for nlog which supports net standard 2 - nlog 4.5

**Comment by 304NotModified** [comment]
Ow missed https://github.com/graffen/NLog.Targets.Syslog/pull/94

Great work @snakefoot !

**Comment by frelis** [comment]
When the #94 will be merged, and a new release made?

**Comment by luigiberrettini** [comment]
A new release will be made as soon as possible; if you have urgent needs please consider forking or cloning and making changes to the desired repository

**Comment by luigiberrettini** [comment]
Reopened because PR #102 was merged on master, but the code was then moved to a branch while waiting for an NLog release supporting .NET Standard.

**Comment by 304NotModified** [comment]
sounds like a force push on the master
