### ISSUE TITLE
Create NLog.Targets.Syslog.Schema NuGet package

### ISSUE THREAD

**Issue by luigiberrettini** [graffen/NLog.Targets.Syslog#63]
- [x] Create nuspec file for the target schema
- [x] Update build script
- [x] Update appveyor.yml

**Comment by luigiberrettini** [comment]
@304NotModified do you think it would be a good idea to publish custom target XSD schemas, via PRs, under the schemas folder of your NLog site repo so that they will all have the url `http://nlog-project.org/schemas/*.xsd`?

**Comment by 304NotModified** [comment]
Yes I like that idea! 

Think we need to add the version also in the URL/filename?

**Comment by luigiberrettini** [comment]
It would be useful if we used different versions for the schema and the target NuGet, but usually, as NLog and the Syslog target do, the schema NuGet version is updated to match the related software NuGet version, even if there are no changes.
This would require creating a lot of PR to your NLog site repo @304NotModified, therefore I suggest not appending the version to XSD files published in your schemas folder.

**Comment by 304NotModified** [comment]
hi @luigiberrettini 

I think users should use 
```xml
<nlog xmlns="http://nlog-project.org/schemas/NLog.Targets.Syslog.xsd"       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

Am I correct? Maybe we should update the example on [readme](https://github.com/graffen/NLog.Targets.Syslog/blob/master/README.md)

**Comment by luigiberrettini** [comment]
This should be the correct set of XMLNSs:

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:sl="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd">
```
