### ISSUE TITLE
Copyright and license

### ISSUE THREAD

**Issue by luigiberrettini** [graffen/NLog.Targets.Syslog#66]
There are a lot of projects adopting the MIT license.
Moreover I looked at NLog and other projects/NuGet packages: most times copyright is not set in AssemblyInfo.cs and `*.nuspec` files, but is present in the source code.

@graffen, @304NotModified  I would be happy to understand rules or just your idea/position on the following questions.
1. Should we adopt it or stay with Apache or use the BSD used by NLog since we depend on it?
2. Should we remove copyright from AssemblyInfo.cs attributes and *.nuspec?
3. Which people should be listed in the source file header copyright notice: all contributors, some or only the original creator of the repo?
4. Is the copyright always of the contributor who commits or shared between him and the repo owner or transferred from the contributor to the repo owner?

Thank you!

**Comment by 304NotModified** [comment]
I have limited knowledge on this, so correct me if wrong:

> 1. Should we adopt it or stay with Apache or use the BSD used by NLog since we depend on it?

I think Apache is fine, but AFAIK MIT and BSD are less limited. Some people prefer MIT/BSD over Apache. E.g. Log4net is Apache.  

Choosing for BSD would be logical as NLog is BSD

> 2. Should we remove copyright from AssemblyInfo.cs attributes and *.nuspec?

Copyright is not the same as license. Only the author who's written it, has the copyright. The author is the only one who can change the copyright. So that's for @graffen

 > 3. Which people should be listed in the source file header copyright notice: all contributors, some or only the original creator of the repo?

Difficult one. All contributors are a lot ;) I would say, the creator and maintainers. 

> 4 Is the copyright always of the contributor who commits or shared between him and the repo owner or transferred from the contributor to the repo owner?

When the contributor send a PR, he hands over the copyright. So transferred.

**Comment by 304NotModified** [comment]
Userful stuf: https://www.whitesourcesoftware.com/whitesource-blog/top-10-apache-license-questions-answered

> 6. What is the difference between Apache License 2.0 and MIT?
> 
> MIT is one of the most permissive free software licenses. Basically, you can do whatever you want with a software licensed under the MIT license - just make sure that you add a copy of the original MIT license and copyright notice to it.
> The Apache License is also a permissive license. However, it has stringent terms when it comes to modifications. It requires you to explicitly list out all the modifications that you’ve done in the original software, i.e., you’re required to preserve modification notices. The Apache License also states clearly that you can’t name your product in any way that hints at the product being endorsed by Apache. So you can call your product “SuperWonderServer powered by Apache” but not “Apache SuperWonderServer”. The MIT license doesn’t impose any such terms.
> The MIT license is also gaining popularity with developers due to its short and clear license agreement, in contrast to the Apache license agreement. Although the Apache License is nearly identical in terms of what you can and can't do, it is much more heavily "lawyered" and is significantly more verbose. Heck, the appendix alone, which explains how to apply the license, is longer than the entire MIT license.
> DOWNLOAD FREE GUIDE: "A SURVIVAL GUIDE TO USING GPL?"
>  
> 7. What is the difference between Apache License 2.0 and BSD?
> 
> The BSD license is another highly permissible license that allows you to modify and redistribute software licensed under the BSD license as you like. Earlier versions of the Apache License were identical to the original (and later the modified) BSD licenses, but Apache License 2.0 sets them apart. The key differences between the two licenses are:
> Explicit grant of patent rights: Apache License 2.0 explicitly lays down the grant of patent rights while using, modifying or distributing Apache licensed software; it also lists the circumstances when such grant gets withdrawn.
> Clear definitions of the used concepts: Apache License 2.0 explicitly defines all the terms and concepts that it uses. This leaves little scope for ambiguity.
> Reusable without rewording: Apache License 2.0 can be easily used by other projects without any rewording in the license document itself.

**Comment by luigiberrettini** [comment]
Ok so if @graffen agrees we could switch to BSD to be aligned with NLog.

I have already written the copyright owned by graffen everywhere using the same words and the starting year (2013): I read that people should not increment copyright year to hold the copyright from the written year on.

My last doubt is if I would be allowed to publish a NuGet package based on code I have created for a project I contributed to: e.g. a NTcp package based on Tcp.cs in the NLog Syslog target.

**Comment by graffen** [comment]
Actually, I think it would make lots of sense to align the license of this package to NLog. So I say go ahead and re-license under the BSD license. As far as I know this should be as simple as updating the license.md file and notifying about the change somewhere in the release notes?

Regarding the questions on Copyright, I believe I own the copyright to my original code but of course cannot claim copyright over code I didn't write myself. So ideally, we should probably list everyone that has contributed code to the project (or simply refer to https://github.com/graffen/NLog.Targets.Syslog/graphs/contributors). In addition, the reason for updating the copyright year is that in most jurisdictions, copyright expires after a certain period of time. So as long as there is active work going on in the library, the copyright year should move along, to reflect this. I'm not a lawyer, so I might be wrong, though :)
