### ISSUE TITLE
Adopt BSD 3-clause license and update copyright info to include contributors

### ISSUE THREAD

**Issue by luigiberrettini** [graffen/NLog.Targets.Syslog#67]
- [x] Update license file
- [x] Update documentation with relation to the license
- [x] Update copyright in AssemblyInfo.cs
- [x] Update copyright in nuspec files
- [x] Add copyright and license info to all source files

As for copyright, consider using a date range and including the [contributors URL](https://github.com/graffen/NLog.Targets.Syslog/graphs/contributors)

See #66 for more information

**Comment by graffen** [comment]
:champagne:
