### ISSUE TITLE
Configure AppVeyor webhook

### ISSUE THREAD

**Issue by luigiberrettini** [graffen/NLog.Targets.Syslog#73]
Hi @graffen, it would be nice if you could [configure AppVeyor](http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests) (I do not have access to repo settings).

Thanks!

**Comment by graffen** [comment]
Sure! @luigiberrettini do you have an AppVeyor user? I think I can add you as a collaborator on the AppVeyor project. You can send me your email address (if you use Keybase you can just dump a text file in our private keybase folder with it :) )

**Comment by luigiberrettini** [comment]
I already created the AppVeyor account and enabled the build, but I cannot configure the webhook: I do not know if you will find it already partially setup by AppVeyor

**Comment by graffen** [comment]
It set up just fine :) https://ci.appveyor.com/project/graffen/nlog-targets-syslog
Can you see this?

**Comment by luigiberrettini** [comment]
Yes I can see it, but I have to send you my e-mail address to be able to admin it :)

**Comment by graffen** [comment]
Correct. If you're on Keybase you can just dump a text file with it in our private keybase folder. If not a Twitter DM could be an option if you don't want to share it here.
