### ISSUE TITLE
Add topics

### ISSUE THREAD

**Issue by luigiberrettini** [graffen/NLog.Targets.Syslog#78]
It would be nice to add the following topics to the GitHub project:
1. logging
2. nlog
3. syslog
4. dotnet
5. library

**Comment by graffen** [comment]
@luigiberrettini By topics, do you mean labels?

**Comment by luigiberrettini** [comment]
![image](https://cloud.githubusercontent.com/assets/4513301/22865014/af44b710-f15b-11e6-8efb-cf4abfa6a199.png)

**Comment by graffen** [comment]
Done :)
