### ISSUE TITLE
IsSocketConnected checks for disconnection

### ISSUE THREAD

**Issue by markdascher** [graffen/NLog.Targets.Syslog#85]
The latest v3.1.0 release of NLog.Targets.Syslog seems to form a new TCP and TLS connection for each individual log message. (Confirmed with a tcpdump.) This limits the maximum log rate to about 1 message per second, unless we start adding extra `messageProcessors`.

Upon further investigation, the older v2 release seems to do roughly the same thing, but performance can be improved by wrapping it in either an [AsyncWrapper](https://github.com/nlog/nlog/wiki/AsyncWrapper-target) or [BufferingWrapper](https://github.com/NLog/NLog/wiki/BufferingWrapper-target). I assume that's because these wrappers deliver multiple events simultaneously, and then NLog.Targets.Syslog can share a single connection for the whole batch.

These wrappers aren't needed (and don't help) for v3, since the target is already asynchronous. The new target accepts each batch immediately, but then requeues them internally, and fires up a new TCP connection for each one.

After some more testing, I just realized that setting `connectionCheckTimeout` to 0 solves the issue, so perhaps #74 is the issue?

**Comment by markdascher** [comment]
After looking a bit closer, I'm wondering if the logic is reversed for [line 69 of IsSocketConnected()](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/master/src/NLog.Targets.Syslog/MessageSend/Tcp.cs#L69):

```
return  tcp.Client.Poll(connectionCheckTimeout, SelectMode.SelectRead) && tcp.Client.Available == 0;
```

But if Poll returns true, and Available is zero, then that would mean the socket is disconnected. Would it work better like this:

```
return !(tcp.Client.Poll(connectionCheckTimeout, SelectMode.SelectRead) && tcp.Client.Available == 0);
```

**Comment by luigiberrettini** [comment]
You are definitely right!
